# Generated by Django 5.0.7 on 2024-08-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('id_teacher', models.IntegerField()),
                ('id_admin', models.IntegerField()),
            ],
        ),
    ]
