# Generated by Django 5.0.8 on 2024-08-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='id_admin',
            new_name='id_student',
        ),
        migrations.RemoveField(
            model_name='score',
            name='id_teacher',
        ),
    ]
